Scripts - Power: Revamp (More changes to be done)

diff --git a/Scripts/Power/Power b/Scripts/Power/Power
--- a/Scripts/Power/Power
+++ b/Scripts/Power/Power
@@ -1,65 +1,93 @@
 #!/bin/bash
 
-if [ "$#" -ge 2 ]; then
-	printf "\033[0;31mError: Too many arguments\033[0m\n"
-	exit 128
-elif [ "$#" -le 0 ]; then
-	printf "\033[0;31mError: No arguments\033[0m\n"
-    echo 'Syntax: Power <OPTION>'
-    echo 'Options:'
-    echo '-s, --shutdown'
-    echo '-r, --reboot'
-    echo '-l, --logout'
-    echo '-f, --firmware'
-	exit 128
-fi
-
-common () {
-    if [[ $? == 1 ]]; then
-        helper=$(pgrep -x Helper)
-        kill -SIGTERM $helper
-        exit 130
-    else
-        killall waybar
-        hyprctl dispatch workspace 15
-        sleep 1
-    fi
+help () {
+  echo 'Syntax: Power <OPTION>'
+  echo 'Options:'
+  echo '-s, --shutdown'
+  echo '-r, --reboot'
+  echo '-l, --logout'
+  echo '-f, --firmware'
+  echo '-h, --help'
 }
 
-shutdown () {
-    $HOME/Scripts/Power/Helper -s & yad --image=dialog-warning --title="Shut down?" --button="Shut down now":0 --button="Cancel":1 --text="Shutting down in 5 seconds"
+if [[ "$#" -le 0 ]] || [[ "$#" -gt 1 ]]; then
+	printf "\033[0;31mError: Please enter one argument\033[0m\n"
+  help
+  exit 1
+fi
 
-    common
-	exec systemctl poweroff
+shutdown () {
+  action () {
+    systemctl poweroff
+  }
+  delayedAction &
+  delayedPID=$(echo $!)
+  yad --image=dialog-warning --title="Shut down?" --button="Shut down now":0 --button="Cancel":1 --text="Shutting down in 5 seconds"
 }
 
 reboot () {
-    $HOME/Scripts/Power/Helper -r & yad --image=dialog-warning --title="Reboot?" --button="Reboot now":0 --button="Cancel":1 --text="Rebooting in 5 seconds"
-    common
-	exec systemctl reboot
+  action () {
+    systemctl reboot
+  }
+  delayedAction &
+  delayedPID=$(echo $!)
+  yad --image=dialog-warning --title="Reboot?" --button="Reboot now":0 --button="Cancel":1 --text="Rebooting in 5 seconds"
 }
 
 logoutFunc () {
-    $HOME/Scripts/Power/Helper -l & yad --image=dialog-warning --title="Log out?" --button="Log out now":0 --button="Cancel":1 --text="Logging out in 5 seconds"
-    common
-	exec hyprctl dispatch exit
+  action () {
+    hyprctl dispatch exit
+  }
+  delayedAction &
+  delayedPID=$(echo $!)
+  yad --image=dialog-warning --title="Log out?" --button="Log out now":0 --button="Cancel":1 --text="Logging out in 5 seconds"
 }
 
 firmware () {
-    $HOME/Scripts/Power/Helper -r & yad --image=dialog-warning --title="Reboot to firmware?" --button="Reboot now":0 --button="Cancel":1 --text="Rebooting to firmware settings in 5 seconds"
-    common
-    exec systemctl reboot --firmware-setup
+  action () {
+    systemctl reboot --firmware-setup
+  }
+  delayedAction &
+  delayedPID=$(echo $!)
+  yad --image=dialog-warning --title="Reboot to firmware?" --button="Reboot now":0 --button="Cancel":1 --text="Rebooting to firmware settings in 5 seconds"
 }
 
-if [ $1 == '-s' ] || [ $1 == '--shutdown' ]; then
-    shutdown
-elif [ $1 == '-r' ] || [ $1 == '--reboot' ]; then
-    reboot
-elif [ $1 == '-l' ] || [ $1 == '--logout' ]; then
-    logoutFunc
-elif [ $1 == '-f' ] || [ $1 == '--firmware' ]; then
-    firmware
+delayedAction () {
+  sleep 5
+  action
+}
+
+common () {
+  if [[ "$?" == 0 ]]; then
+    action
+  else
+    kill -SIGTERM $delayedPID
+    echo 'Cancelled'
+    exit 0
+  fi
+}
+
+
+if [[ "$1" == '-s' ]] || [[ "$1" == '--shutdown' ]]; then
+  shutdown
+elif [[ "$1" == '-r' ]] || [[ "$1" == '--reboot' ]]; then
+  reboot
+elif [[ "$1" == '-l' ]] || [[ "$1" == '--logout' ]]; then
+  logoutFunc
+elif [[ "$1" == '-f' ]] || [[ "$1" == '--firmware' ]]; then
+  firmware
 else
+  if [[ "$1" == '-h' ]] || [[ "$1" == '--help' ]]; then
+    help
+    exit 0
+  else
     printf "\033[0;31mError: Invalid argument\033[0m\n"
-    exit 128
+    help
+    exit 1
+  fi
 fi
+
+common
+
+exit 0
+
